# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-11 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='ListUsers',
        ),
        migrations.AddField(
            model_name='post',
            name='enable',
            field=models.SmallIntegerField(default=0),
        ),
    ]
